services:

  postgres:
    image: postgres:15
    container_name: sh-postgres
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: rabbitmq:3-management
    container_name: sh-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7
    container_name: sh-redis
    command: ["redis-server", "--requirepass", "redispass"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build: ../backend/AuthService
    container_name: sh-authentication
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=authdb;Username=postgres;Password=admin
    ports:
      - "5001:8080"

  appointment-service:
    build: ../backend/AppointmentService
    container_name: sh-appointment
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=appointmentdb;Username=postgres;Password=admin
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Password: guest
      Redis__ConnectionString: redis:6379,password=redispass,abortConnect=False
    ports:
      - "8080:8080"


  notification-service:
    build: ../backend/NotificationService
    container_name: sh-notification
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RabbitMQ__Host: rabbitmq
      RabbitMQ__User: guest
      RabbitMQ__Password: guest
    restart: always


  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: sh-prometheus
    depends_on:
      appointment-service:
        condition: service_started
      notification-service:
        condition: service_started
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana:10.4.2
    container_name: sh-grafana
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"


volumes:
  pgdata:
