apiVersion: v1
kind: Secret

metadata:
  name: smarthealth-secrets

type: Opaque

data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4=
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
  REDIS_PASSWORD: cmVkaXNwYXNz
  API_KEY: Y2hhbmdlLW1l
