apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: backend-admin-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

            - name: DB_HOST
              value: postgres  

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: admindb    

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: smarthealth-secrets
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smarthealth-secrets
                  key: POSTGRES_PASSWORD

            - name: Jwt__Key
              value: this-is-a-very-secure-super-long-key-123456789

            - name: Jwt__Issuer
              value: auth-service

            - name: Jwt__Audience
              value: smart-healthcare