apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: backend-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
# internal api key for inter-service communication
            - name: InternalAuth__ApiKey
              valueFrom:
                secretKeyRef:
                  name: smarthealth-secrets
                  key: INTERNAL_API_KEY
                  
# Email service connection settings
            - name: SendGrid__ApiKey
              valueFrom:
                secretKeyRef:
                  name: sendgrid-secret
                  key: SendGrid__ApiKey
            
            - name: SendGrid__FromEmail
              valueFrom:
                secretKeyRef:
                  name: sendgrid-secret
                  key: SendGrid__FromEmail

            - name: SendGrid__FromName
              valueFrom:
                secretKeyRef:
                  name: sendgrid-secret
                  key: SendGrid__FromName

# Database connection settings
            - name: DB_HOST
              value: postgres

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: authdb

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: smarthealth-secrets
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smarthealth-secrets
                  key: POSTGRES_PASSWORD
                  
            - name: Jwt__Key
              value: this-is-a-very-secure-super-long-key-123456789
            - name: Jwt__Issuer
              value: auth-service
            - name: Jwt__Audience
              value: smart-healthcare