apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: backend-patient-service:latest
          imagePullPolicy: Never   
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development

            - name: DB_HOST
              value: postgres

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: patientdb

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: smarthealth-secrets
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smarthealth-secrets
                  key: POSTGRES_PASSWORD

            - name: Jwt__Key
              value: this-is-a-very-secure-super-long-key-123456789

            - name: Jwt__Issuer
              value: auth-service

            - name: Jwt__Audience
              value: smart-healthcare
            
            - name: AUTH_SERVICE_URL
              value: http://auth-service

            - name: InternalApiKey
              valueFrom:
                secretKeyRef:
                  name: smarthealth-secrets
                  key: INTERNAL_API_KEY
            
            - name: ServiceName
              value: "patient-service"