apiVersion: v1
kind: Secret

metadata:
  name: smarthealth-secrets

type: Opaque

stringData:
  POSTGRES_USER: "change-me"
  POSTGRES_PASSWORD: "change-me"
  RABBITMQ_DEFAULT_USER: "change-me"
  RABBITMQ_DEFAULT_PASS: "change-me"
  REDIS_PASSWORD: "change-me"
  API_KEY: "change-me"
  STRIPE_SECRET_KEY: "change-me"
  STRIPE_PUBLISHABLE_KEY: "change-me"
  STRIPE_WEBHOOK_SECRET: "change-me"

--- #this part is important btw or you can just set send grid part in a different sendgridsecrets.yaml too
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-secret
type: Opaque
stringData:
  SendGrid__ApiKey: "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"
  SendGrid__FromEmail: "gavindurushel@gmail.com"
  SendGrid__FromName: "SmartHealth"