{
 "title": "SmartHealth Metrics",
 "refresh": "10s",
 "panels": [
  {
   "title": "Appointments Created",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "appointments_created_total" }
   ]
  },
  {
   "title": "Appointments Cancelled",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "appointments_cancelled_total" }
   ]
  },
  {
   "title": "Booking Conflicts",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "appointments_conflict_total" }
   ]
  },
  {
   "title": "RabbitMQ Publish Success",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "rabbitmq_publish_success_total" }
   ]
  },
  {
   "title": "RabbitMQ Publish Failure",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "rabbitmq_publish_failure_total" }
   ]
  }
 ]
}